### ISSUE TITLE
Discard duplicate data

### ISSUE THREAD

**Issue by gringus** [unixsurfer/haproxystats#5]
Due to HAProxy misconfiguration or lazyness we may end up in situation where the very same process is mapped to different sockets eg.

```
global
    nbproc             1
    stats   socket     /run/haproxy-1.sock mode 660 level admin process 1
    stats   socket     /run/haproxy-2.sock mode 660 level admin process 2

```

Haproxy will expose process 1 over socket 1 & 2 and not only socket 1:

```
bash$ echo 'show info' | socat - UNIX-CONNECT:/run/haproxy-1.sock|fgrep Pid
Pid: 4584
bash$ echo 'show info' | socat - UNIX-CONNECT:/run/haproxy-2.sock|fgrep Pid
Pid: 4584
```

This will lead to a situation when our statistics double as we aggregate the very same data twice. Haproxystats daemon should discard duplicate data from duplicate sockets which can be identified by **Pid** (probably the best option). Additionally consistency of sockets / processes can be verified using **Process_num** & **Nbproc**, so re-reading of sockets / directory containing sockets might be required if things do not match (we do not collect data from all processes).

**Comment by unixsurfer** [comment]
This is a misconfiguration for which HAProxy emits a warning on startup but it allows to access a single process from 2 sockets. I looked at possible ways to catch this misconfiguration and do something about it, either ignore the stats and emit a critical log messages or perform some aggregation.
The PID and the stats are saved in 2 different files (PID is in admin1.sock_info file and stats in admin1.sock_stat file) which means we need to parse all files, find possible duplicates and then perform the aggregation. In the example configuration you mentioned it could be easy to do such thing, but if someone has 3 processes (nbproc =3 ) and 8 stats socket configured then what we can do? 

I am afraid I have to complicate things in order to catch a misconfiguration from a user, for which HAProxy emits already a warning. Thus, I am going to close this as wont fix
