### ISSUE TITLE
Error On haproxystats-process Log

### ISSUE THREAD

**Issue by hos7ein** [unixsurfer/haproxystats#8]
Hi

I use this config for haproxystats :

https://paste.fedoraproject.org/paste/cm6x7Y9ou91ZbFy6vwP69F5M1UNdIGYhyRLivL9gydE=

First run this command for start haproxystats-pull :

> # haproxystats-pull -f /etc/haproxystats.conf

and run this command for start  haproxystats-process :

># haproxystats-process -f /etc/haproxystats.conf

when I look at the  haproxystats-process log I see a Message WARNING and ERROR . this below is part of log :

https://paste.fedoraproject.org/paste/e9o5d9kOg8M8KoeMnVA2zl5M1UNdIGYhyRLivL9gydE=

I use of docker-grafana-graphite  ( https://github.com/kamon-io/docker-grafana-graphiteHowever ) and  I can’t see anythings on Grafana/Graphite.

How can fix this?

Tnx

**Comment by unixsurfer** [comment]
From the following log lines, I can see that we got a **broken pipe** error while we were sending data to 10.10.22.185 and then we successfully reopened the connection to that node. The **broken pipe** suggests that we received a TCP RST during the transfer. If you could tcpdump the traffic during the issue then we can confirm this.  There isn't nothing wrong on haproxystats-process side.


2017-04-23 14:53:08,057 [16277] [Consumer-2 ] [send                ] ERROR    caught [Errno 32] Broken pipe while sending data to graphite
2017-04-23 14:53:08,058 [16277] [Consumer-2 ] [send                ] WARNING  10.0 secs since last failure
2017-04-23 14:53:08,058 [16277] [Consumer-2 ] [send                ] INFO     TCP info: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.22.186', 57302)>
2017-04-23 14:53:08,058 [16277] [Consumer-2 ] [close               ] INFO     closing connection to 10.10.22.185 on port 81
2017-04-23 14:53:08,058 [16277] [Consumer-2 ] [close               ] INFO     TCP info: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.22.186', 57302)>
2017-04-23 14:53:08,058 [16277] [Consumer-2 ] [close               ] INFO     successfully closed connection to 10.10.22.185 on port 81
2017-04-23 14:53:08,058 [16277] [Consumer-2 ] [_create_connection  ] INFO     connecting to 10.10.22.185 on port 81
2017-04-23 14:53:08,059 [16277] [Consumer-2 ] [open                ] INFO     successfully connected to 10.10.22.185 on port 81, TCP info <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.22.186', 58184), raddr=('10.10.22.185', 81)>

**Comment by hos7ein** [comment]
this is a part of haproxystats-process log : 
https://paste.fedoraproject.org/paste/UBWZ6femz6BU0OokLZwLZ15M1UNdIGYhyRLivL9gydE=

and on the graphite server by ip=10.10.22.185:81 run this command : 

>  #  tcpdump -i enp0s3  -n src 10.10.22.186 and dst port 81
here is part of tcpdump log : 

https://paste.fedoraproject.org/paste/zwh5tBXD8y29VEX6mHaEBV5M1UNdIGYhyRLivL9gydE=

tnx @unixsurfer

**Comment by unixsurfer** [comment]
with the above filter in tcpdump you **only** captured the packets sent by haproxystats-process and not the packets from graphite entry point. Therefore, we can not see if graphite entry point has sent TCP RST. Please remove the *dst* from the filter.

**Comment by hos7ein** [comment]
tnx @unixsurfer 

this is a part of haproxy-process log : 
https://paste.fedoraproject.org/paste/U5y9yfafk3FndihNqC1m2l5M1UNdIGYhyRLivL9gydE=

run this command on graphite server : 

>  tcpdump -i enp0s3  -n src 10.10.22.186

and here is part of tcpdump log on graphite server : 
https://paste.fedoraproject.org/paste/8xsm42pnQWeb2giHItIWzF5M1UNdIGYhyRLivL9gydE=

**Comment by unixsurfer** [comment]
please remove the *src* filter as it prevents capturing packet sent by graphite point.....

**Comment by hos7ein** [comment]
run this command : 

> tcpdump -i enp0s3  -n

and here is tcpdump log on graphite server : 
https://paste.fedoraproject.org/paste/Cp-PxqtH8jJGfASUkA-4nF5M1UNdIGYhyRLivL9gydE=


tnx @unixsurfer

**Comment by unixsurfer** [comment]
you forgot to include the log, but your tcpdump is too verbose as it has packets for ssh traffic. Try the following to capture packets only between your server and graphite.
tcpdump -i enp0s3 -n host 10.10.22.186 and host 10.10.22.185 and port 81

Don't forget to include the haproxylog and please make sure the tcpdump and log start from the same time period.

**Comment by unixsurfer** [comment]
To make your life easier just save the traffic in a file:
 tcpdump -i enp0s3 -s0 -w issue.pcap

and I will do the filtering. Please don't forget to include the log.

**Comment by hos7ein** [comment]
this is a haproxy-process log : 
https://paste.fedoraproject.org/paste/LbnUldz9GfoiIj08zBlwH15M1UNdIGYhyRLivL9gydE=

and then run "tcpdump -i enp0s3 -n host 10.10.22.186 and host 10.10.22.185 and port 81" on graphite server and here is tcpdump log : 
https://paste.fedoraproject.org/paste/M2JeuVHPuoG2pd2zcuYiel5M1UNdIGYhyRLivL9gydE=



The second method is : 

haproxy-process log : 
https://paste.fedoraproject.org/paste/MW9NzQ3GUCMxLn0NEkBRqV5M1UNdIGYhyRLivL9gydE=

and here is pcap file : 
http://dl2.fedorafans.com/dl/issue.pcap


tnx @unixsurfer

**Comment by unixsurfer** [comment]
In the pcap file I see that server returned:
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

and then we got TCP RST from web servers, which is quite normal.
This indicates that you configured haproxystats-process to send data to a HTTP server, that will never work as metrics are sent over plain TCP.

**Comment by unixsurfer** [comment]
I am going to close it as this is a configuration issue, haproxystats-process is configured to send metrics to a web server rather to a server that understand graphite data.
